# -*- coding: utf-8 -*-
"""Taller 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18DtGLObm_GGSh3t9g4x8UpxUqQwzUwII

Implementa una función no recursiva que cuente el número de
dígitos en un número entero.
"""

def contar_digitos_numero_entero(numero):    #O(n)
    contador = 0 #O(0) #O(1)
    numero = abs(numero) #O(0) #O(1)


    while numero > 0:  #O(n)
        contador += 1  #O(n)
        numero //= 10  #O(n)

    return contador #O(0)

numero = 170943876  #O(0) #O(1)
print("El número de dígitos en", numero, "es:", contar_digitos_numero_entero(numero))  #O(0)

"""Crea una función no recursiva que sume todos los elementos de un array."""

def sumar_array(array):  #O(n)
    suma = 0 #O(0) #O(1)
    for elemento in array: #O(n)
        suma += elemento  #O(n)
    return suma #O(0)


array = [6, 2, 9, 4]  #O(0) #O(1)
print("La suma de los elementos del array es:", sumar_array(array)) #O(0)

"""Desarrolla una función no recursiva que sume todos los dígitos de un número entero"""

def sumar_digitos_numero_entero(numero): #O(n)
    suma = 0  #O(0) #O(1)
    numero = abs(numero)  #O(0) #O(1)


    while numero > 0: #O(n)
        ultimo_digito = numero % 10 #O(n) #O(1)
        suma += ultimo_digito #O(n)
        numero //= 10 #O(n)

    return suma #O(0)


numero = 74325  #O(0) #O(1)
print("La suma de los dígitos del número entero", numero, "es:", sumar_digitos_numero_entero(numero))  #O(0)